import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  keyboardView: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  content: {
    backgroundColor: '#FFF8E8',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    maxHeight: '90%',
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    position: 'relative',
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0c4309',
  },
  closeButton: {
    position: 'absolute',
    right: 0,
    padding: 4,
  },
  closeText: {
    fontSize: 18,
    color: '#49454F',
    fontWeight: '500',
  },
  loadingContainer: {
    paddingVertical: 60,
    alignItems: 'center',
  },
  providerSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5DCC9',
  },
  providerRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  providerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#0c4309',
    justifyContent: 'center',
    alignItems: 'center',
  },
  providerAvatarImage: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  providerInitials: {
    fontSize: 17,
    fontWeight: '700',
    color: 'white',
  },
  providerInfo: {
    marginLeft: 12,
    flex: 1,
  },
  providerName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0c4309',
  },
  providerRating: {
    fontSize: 14,
    color: '#49454F',
    marginTop: 2,
  },
  scheduledTimeRow: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5DCC9',
  },
  scheduledTimeText: {
    fontSize: 14,
    color: '#49454F',
    textAlign: 'center',
  },
  summarySection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5DCC9',
  },
  receiptHeader: {
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E5DCC9',
    borderStyle: 'dashed',
  },
  receiptTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#49454F',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  summaryLabel: {
    fontSize: 15,
    color: '#333333',
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333333',
  },
  dividerLine: {
    height: 1,
    backgroundColor: '#E5DCC9',
    marginVertical: 8,
  },
  feeLabel: {
    fontSize: 14,
    color: '#6B6B6B',
  },
  feeValue: {
    fontSize: 14,
    color: '#6B6B6B',
  },
  totalRow: {
    borderTopWidth: 2,
    borderTopColor: '#0c4309',
    marginTop: 10,
    paddingTop: 12,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0c4309',
  },
  totalValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0c4309',
  },
  paymentSection: {
    marginBottom: 16,
  },
  paymentSectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#0c4309',
    marginBottom: 10,
  },
  paymentMethodItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E5DCC9',
    marginBottom: 8,
  },
  paymentMethodItemSelected: {
    borderColor: '#0c4309',
    borderWidth: 2,
  },
  paymentMethodInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  paymentMethodIconWrapper: {
    width: 40,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentMethodIcon: {
    width: 32,
    height: 24,
    resizeMode: 'contain',
  },
  paymentMethodBrandEmblem: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0c4309',
    textAlign: 'center',
  },
  paymentMethodBrand: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333333',
  },
  paymentMethodDetails: {
    fontSize: 13,
    color: '#49454F',
    marginTop: 2,
  },
  paymentMethodSelectedIcon: {
    color: '#0c4309',
    fontSize: 18,
    fontWeight: '700',
  },
  editPaymentButton: {
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  editPaymentButtonText: {
    color: '#0c4309',
    fontSize: 16,
    fontWeight: '600',
  },
  addPaymentButton: {
    backgroundColor: '#E5DCC9',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 8,
  },
  addPaymentButtonText: {
    color: '#0c4309',
    fontSize: 14,
    fontWeight: '600',
  },
  noPaymentText: {
    fontSize: 14,
    color: '#49454F',
    textAlign: 'center',
    marginBottom: 12,
  },
  confirmButton: {
    backgroundColor: '#0c4309',
    borderRadius: 24,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 4,
  },
  confirmButtonDisabled: {
    opacity: 0.5,
  },
  confirmButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  cancelButton: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#49454F',
    fontSize: 15,
    fontWeight: '500',
  },
});
