import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#fff0cfff',
  },
  container: {
    flex: 1,
  },
  contentArea: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  panel: {
    height: '66%',
    backgroundColor: '#FFF8E8',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 12,
  },
  panelContent: {
    flex: 1,
    padding: 16,
    paddingBottom: 24,
    justifyContent: 'space-between',
  },
  title: {
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '600',
    color: '#0c4309',
    marginBottom: 6,
    marginTop: 2,
  },
  DividerContainer1: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 6,
    marginBottom: 12,
  },
  DividerLine1: {
    width: 375,
    height: 1,
    backgroundColor: '#cfbf9dff',
  },

  // Location Section
  locationSection: {
    backgroundColor: '#E5DCC9',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginBottom: 0,
    position: 'relative',
    paddingTop: 3,
    paddingBottom: 3,
  },
  locationSectionStart: {
    zIndex: 30,
  },
  locationSectionEnd: {
    zIndex: 20,
  },
  locationSection2: {
    backgroundColor: '#E5DCC9',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingLeft: 6,
    paddingRight: 0,
    marginBottom: 5,
    position: 'relative',
    paddingTop: 3,
    paddingBottom: 4,
  },
  locationSectionEndDropdownVisible: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  locationDividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E5DCC9',
    height: 1,
  },
  locationDividerFill: {
    flex: 1,
    height: 1,
    backgroundColor: '#E5DCC9',
  },
  locationDividerLine: {
    width: '93%',
    height: 0.75,
    backgroundColor: '#cfbf9dff',
  },
  locationLabelRow: {
    marginTop: 6,
    marginBottom: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  confirmLocationIcon: {
    marginLeft: 14,
    marginRight: 0,
    marginTop: 2,
  },
  confirmLocationIcon2: {
    marginLeft: 12,
    marginRight: 2,
  },
  locationClearButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#E5DCC9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationClearButtonText: {
    fontSize: 18,
    color: '#7C7160',
    lineHeight: 20,
    fontWeight: '500',
  },

  // Job Description
  jobDescriptionContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginTop: 5,
    marginBottom: 5,
    height: 135,
    borderColor: '#00000019',
    borderWidth: 1,
    overflow: 'hidden',
  },
  jobDescriptionText: {
    color: '#333333',
    fontSize: 17,
    textAlign: 'left',
    textAlignVertical: 'top',
    paddingLeft: 16,
    paddingRight: 20,
    paddingBottom: 10,
    paddingTop: 12,
    maxHeight: 75,
  },

  // Map
  mapContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '55%',
  },
  map: {
    flex: 1,
  },
  mapMarkerStartIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  mapMarkerEndIcon: {
    width: 26,
    height: 26,
    resizeMode: 'contain',
  },
  mapPlaceholder: {
    flex: 1,
    backgroundColor: '#E5DCC9',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 170,
  },
  confirmLocationIconLarge: {
    width: 96,
    height: 96,
    resizeMode: 'contain',
  },

  // Sliders
  slidersWrapper: {
    paddingHorizontal: 16,
    marginTop: 8,
  },
  binarySliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginVertical: 10,
    marginTop: 14,
  },
  binarySliderContainerNested: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  sliderRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  binarySliderLabel: {
    fontWeight: '500',
    minWidth: 50,
    textAlign: 'left',
    lineHeight: 15,
  },
  isAutoSliderTitle: {
    color: '#0c4309',
    fontSize: 15,
    fontWeight: 'bold',
  },
  isAutoSliderSubtitle: {
    color: '#0c4309',
    fontSize: 13,
    fontWeight: 'normal',
  },
  isPersonalSliderTitle: {
    color: '#0c4309',
    fontSize: 15,
    fontWeight: 'bold',
  },
  isPersonalSliderSubtitle: {
    color: '#0c4309',
    fontSize: 13,
    fontWeight: 'normal',
  },
  binarySlider: {
    width: 68,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E5DCC9',
    justifyContent: 'center',
    padding: 4,
    overflow: 'hidden',
  },
  binarySliderThumb: {
    width: 36,
    height: 36,
    borderRadius: 22,
    backgroundColor: '#8a7956ad',
    position: 'absolute',
    left: 0,
  },
  binarySliderIcons: {
    position: 'absolute',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    pointerEvents: 'none',
    zIndex: 1001,
  },
  binarySliderIcons2: {
    position: 'absolute',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    paddingLeft: 6,
    pointerEvents: 'none',
    zIndex: 1001,
  },
  binarySliderIcon: {
    width: 20,
    height: 20,
  },
  binarySliderIcon2: {
    width: 24,
    height: 24,
  },
  BusinessPMIcon: {
    width: 20,
    height: 20,
    marginLeft: 8,
    marginTop: 1,
  },
  pmIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pmIcon: {
    width: 24,
    height: 24,
  },
  arrowIcon: {
    width: 14,
    height: 14,
  },

  // Bottom Row / Schedule Button
  bottomRowContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 8,
  },
  scheduleHelprContainer: {
    backgroundColor: '#0c4309',
    borderRadius: 30,
    width: '100%',
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  scheduleHelprText: {
    color: '#FFFFFF',
    fontSize: 19,
    fontWeight: 'bold',
    textAlign: 'center',
  },

  // Thumbnails
  thumbnailsListModal: {
    width: '100%',
    paddingVertical: 6,
  },
  thumbnailsScrollModal: {
    alignItems: 'center',
    paddingLeft: 6,
  },
  thumbnailImage: {
    width: 56,
    height: 42,
    borderRadius: 6,
    resizeMode: 'cover',
  },
  thumbnailRemoveButton: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5dcc9',
  },
  thumbnailRemoveText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#b02a2a',
    lineHeight: 16,
  },
  thumbnailWrapperModal: {
    width: 64,
    height: 48,
    marginRight: 8,
    position: 'relative',
  },
  thumbnailAddButton: {
    width: 56,
    height: 42,
    marginRight: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E5DCC9',
    backgroundColor: '#FFF8E8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  thumbnailAddText: {
    fontSize: 24,
    color: '#0c4309',
    lineHeight: 24,
    fontWeight: '600',
  },
  thumbnailAddContainerModal: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 6,
  },
  thumbnailAddLabelTextModal: {
    marginLeft: 8,
    fontSize: 12,
    fontWeight: '600',
    color: '#0c4309',
  },

  // Moving Analysis Modal
  movingAnalysisOverlayBackground: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyboardAvoidingView: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  movingAnalysisModal: {
    width: '85%',
    backgroundColor: '#FFF8E8',
    borderRadius: 30,
    paddingTop: 20,
    paddingBottom: 20,
    paddingHorizontal: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  movingAnalysisTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0c4309',
    textAlign: 'center',
    marginBottom: 15,
  },
  movingAnalysisMessage: {
    fontSize: 14,
    fontWeight: '500',
    color: '#0c4309',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 20,
  },
  movingAnalysisInput: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: '#333333',
    borderWidth: 1,
    borderColor: '#E5DCC9',
    marginBottom: 15,
    textAlignVertical: 'top',
  },
  movingAnalysisOptionsContainer: {
    width: '100%',
    marginBottom: 20,
  },
  movingAnalysisOption: {
    backgroundColor: '#E5DCC9',
    borderRadius: 10,
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#E5DCC9',
  },
  movingAnalysisOptionSelected: {
    backgroundColor: '#0c4309',
    borderColor: '#0c4309',
  },
  movingAnalysisOptionText: {
    fontSize: 16,
    color: '#0c4309',
    fontWeight: '500',
    textAlign: 'center',
  },
  movingAnalysisOptionTextSelected: {
    color: '#FFFFFF',
  },
  movingAnalysisButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 12,
  },
  movingAnalysisButton: {
    flex: 1,
    backgroundColor: '#0c4309',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  movingAnalysisButtonDisabled: {
    backgroundColor: '#cccccc',
    opacity: 0.5,
  },
  movingAnalysisButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  movingAnalysisCancelButton: {
    flex: 1,
    backgroundColor: '#E5DCC9',
    borderRadius: 25,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderWidth: 2,
    borderColor: '#0c4309',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  movingAnalysisCancelButtonText: {
    color: '#0c4309',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  movingAnalysisSkipRowBelow: {
    width: '100%',
    alignItems: 'center',
    marginTop: 8,
  },
  movingAnalysisSkipButton: {
    backgroundColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  movingAnalysisSkipText: {
    color: '#0c4309',
    fontSize: 16,
    fontWeight: '600',
  },

  // Payment Modal
  paymentModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  paymentModalContent: {
    backgroundColor: '#FFF8E8',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
    maxHeight: '80%',
  },
  paymentModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  paymentModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0c4309',
  },
  paymentModalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5DCC9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentModalCloseText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
  },
  paymentLoadingContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  paymentCardFieldContainer: {
    marginBottom: 24,
  },
  paymentCardField: {
    width: '100%',
    height: 50,
  },
  paymentCardFieldStyle: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5DCC9',
    fontSize: 16,
    textColor: '#0c4309',
  } as any,
  paymentModalActions: {
    gap: 12,
  },
  paymentSaveButton: {
    backgroundColor: '#0c4309',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  paymentSaveButtonDisabled: {
    backgroundColor: '#C0B9A6',
  },
  paymentSaveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  paymentSaveButtonTextDisabled: {
    color: '#E5DCC9',
  },
  savedPaymentMethodsList: {
    marginBottom: 20,
  },
  savedPaymentMethodItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 9,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5DCC9',
    marginBottom: 12,
  },
  savedPaymentMethodItemSelected: {
    backgroundColor: '#E5DCC9',
    borderColor: '#0c4309',
  },
  savedPaymentMethodInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  savedPaymentMethodIconWrapper: {
    width: 40,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    backgroundColor: 'transparent',
  },
  savedPaymentMethodIcon: {
    width: 32,
    height: 20,
  },
  savedPaymentMethodBrand: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0c4309',
  },
  savedPaymentMethodDetails: {
    fontSize: 13,
    color: '#666',
    marginTop: 4,
  },
  savedPaymentMethodSelectedIcon: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0c4309',
  },
  addNewPaymentMethodButton: {
    backgroundColor: '#0c4309',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginBottom: 12,
  },
  addNewPaymentMethodButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFF8E8',
  },
  paymentCancelButton: {
    backgroundColor: '#F8F9FA',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5DCC9',
  },
  paymentCancelButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#666',
  },

  // Plaid
  plaidOptionContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 20,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#E5DCC9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  plaidOptionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  plaidLogo: {
    width: 40,
    height: 40,
    marginRight: 16,
  },
  plaidOptionTextContainer: {
    flex: 1,
  },
  plaidOptionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0c4309',
    marginBottom: 4,
  },
  plaidOptionSubtitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
  },
  plaidOptionArrowText: {
    fontSize: 32,
    fontWeight: '300',
    color: '#0c4309',
    marginLeft: 8,
  },
});






