import { RouteServiceConfig, SingleLocationServiceConfig } from './serviceComposer.types';

export const cleaningServiceConfig: SingleLocationServiceConfig = {
  returnPath: '/(services)/cleaning',
  resumeAction: 'schedule-cleaning',
  serviceType: 'cleaning',
  servicePhrase: 'cleaning',
  screenTitle: 'Cleaning Details',
  locationPlaceholder: 'Cleaning Location',
  descriptionPlaceholder: "Describe your task...                                         (e.g.  'I need my one bedroom apartment deep cleaned.')",
  typeModalTitle: 'Select Cleaning Type',
  typeModalMessage: 'Please select the type of cleaning you need:',
  typeRequiredMessage: 'Please select a cleaning type.',
  typeLogLabel: 'cleaning type',
  typeOptions: [
    {
      value: 'basic',
      label: 'Basic Cleaning',
      description: 'General tidying, dusting, vacuuming, and surface cleaning',
      written: 'Basic cleaning',
    },
    {
      value: 'deep',
      label: 'Deep Cleaning',
      description: 'Comprehensive cleaning including baseboards, inside appliances, and hard-to-reach areas',
      written: 'Deep cleaning',
    },
  ],
  typeEnhancedPattern: '\\.\\s*type:\\s*(basic|deep)\\s*cleaning',
  sizeWrittenLabel: 'Property size',
  sizeExtractPattern: '\\.\\s*Property size:\\s*([^.]+)',
  sizeStripPattern: '\\.\\s*Property size:\\s*[^.]+',
  typeExtractPattern: '\\.\\s*Type:\\s*(Basic|Deep)\\s*cleaning',
  typeStripPattern: '\\.\\s*Type:\\s*(Basic|Deep)\\s*cleaning',
  inferTypeFromDescription: true,
  includeSpelledOutRoomDetection: true,
  sizeDetectPattern: '\\.\\s*property size:',
  sizeLogLabel: 'property size',
  bringDetectPattern: '\\.\\s*supplies to bring:',
  bringWrittenLabel: 'Supplies to bring',
  bringExtractPattern: '\\.\\s*Supplies to bring:\\s*([^.]+)',
  bringStripPattern: '\\.\\s*Supplies to bring:\\s*[^.]+',
  bringLogLabel: 'supplies',
  bringModalTitle: 'Cleaning Supplies',
  bringModalMessage: 'What cleaning supplies or equipment should your Helpr bring?',
  bringPlaceholder: 'e.g., All cleaning supplies, vacuum, mop, eco-friendly products...',
  pricingSystemPrompt: "You are a pricing assistant for cleaning services. Respond with a JSON object containing: price (number), needs_clarification (boolean), clarification_prompt (string, only if needs_clarification is true), safety_concern (boolean), safety_message (string, only if safety_concern is true). Analyze the task description and determine if critical details are missing: 1) degree of cleaning needed (light/medium/deep), 2) which rooms or entire home, 3) property size. If any are unclear, set needs_clarification to true and provide a friendly clarification_prompt asking for the missing details. If the request involves hazardous materials, biohazards, or dangerous conditions, set safety_concern to true with an appropriate safety_message. For complete descriptions, provide price in USD (20-250 range). IMPORTANT: Scale prices significantly based on property size - Studio: $20-40 (basic) / $40-80 (deep), 1-bed: $30-50 (basic) / $60-100 (deep), 2-bed: $45-70 (basic) / $90-130 (deep), 3-bed: $60-90 (basic) / $120-170 (deep), 4+ bed or house: $80-130 (basic) / $150-250 (deep). Always increase price proportionally with more bedrooms. Provide competitive, budget-friendly estimates.",
};

export const furnitureAssemblyServiceConfig: SingleLocationServiceConfig = {
  returnPath: '/(services)/furniture-assembly',
  resumeAction: 'schedule-furniture-assembly',
  serviceType: 'furniture-assembly',
  servicePhrase: 'furniture assembly',
  screenTitle: 'Furniture Assembly Details',
  locationPlaceholder: 'Cleaning Location',
  descriptionPlaceholder: "Describe your task...                                         (e.g.  'I need my one bedroom apartment complex cleaned.')",
  typeModalTitle: 'Select Assembly Complexity',
  typeModalMessage: 'Please select the complexity of your furniture assembly:',
  typeRequiredMessage: 'Please select a assembly complexity.',
  typeLogLabel: 'assembly complexity',
  typeOptions: [
    {
      value: 'simple',
      label: 'Simple Assembly',
      description: 'Basic furniture items like chairs, small tables, or simple shelves',
      written: 'Simple assembly',
    },
    {
      value: 'complex',
      label: 'Complex Assembly',
      description: 'Large or intricate items like bed frames, wardrobes, entertainment centers, or multiple pieces',
      written: 'Complex assembly',
    },
  ],
  typeEnhancedPattern: '\\.\\s*type:\\s*(simple|complex)\\s*cleaning',
  sizeWrittenLabel: 'Property size',
  sizeExtractPattern: '\\.\\s*Property size:\\s*([^.]+)',
  sizeStripPattern: '\\.\\s*Property size:\\s*[^.]+',
  typeExtractPattern: '\\.\\s*Type:\\s*(Basic|Deep)\\s*cleaning',
  typeStripPattern: '\\.\\s*Type:\\s*(Basic|Deep)\\s*cleaning',
  inferTypeFromDescription: false,
  includeSpelledOutRoomDetection: false,
  sizeDetectPattern: '\\.\\s*number and size of furniture pieces:',
  sizeLogLabel: 'number and size of furniture pieces',
  bringDetectPattern: '\\.\\s*tools to bring:',
  bringWrittenLabel: 'Tools to bring',
  bringExtractPattern: '\\.\\s*Tools to bring:\\s*([^.]+)',
  bringStripPattern: '\\.\\s*Tools to bring:\\s*[^.]+',
  bringLogLabel: 'tools',
  bringModalTitle: 'Cleaning Tools',
  bringModalMessage: 'What cleaning tools or equipment should your Helpr bring?',
  bringPlaceholder: 'e.g., All cleaning tools, vacuum, mop, eco-friendly products...',
  pricingSystemPrompt: "You are a pricing assistant for furniture assembly services. Respond with a JSON object containing: price (number), needs_clarification (boolean), clarification_prompt (string, only if needs_clarification is true), safety_concern (boolean), safety_message (string, only if safety_concern is true). Analyze the task description and determine if critical details are missing: 1) complexity of assembly (simple/moderate/complex), number of furniture pieces, 2) types of furniture items to assemble, 3) number and size of furniture pieces. If any are unclear, set needs_clarification to true and provide a friendly clarification_prompt asking for the missing details. If the request involves hazardous materials, biohazards, or dangerous conditions, set safety_concern to true with an appropriate safety_message. For complete descriptions, provide price in USD (30-300 range). IMPORTANT: Scale prices based on item complexity and quantity - Small item (chair, small table): $30-60 (simple) / $60-100 (complex), Medium item (desk, bookshelf): $50-90 (simple) / $90-150 (complex), Large item (bed frame, wardrobe): $80-130 (simple) / $130-200 (complex), Multiple items or very large (entertainment center, sectional): $120-180 (simple) / $180-300 (complex). Always increase price proportionally with more items and complexity. Provide competitive, budget-friendly estimates.",
};

export const homeImprovementServiceConfig: SingleLocationServiceConfig = {
  returnPath: '/(services)/home-improvement',
  resumeAction: 'schedule-home-improvement',
  serviceType: 'home-improvement',
  servicePhrase: 'home improvement',
  screenTitle: 'Home Improvement Details',
  locationPlaceholder: 'Cleaning Location',
  descriptionPlaceholder: "Describe your task...                                         (e.g.  'I need my one bedroom apartment renovation cleaned.')",
  typeModalTitle: 'Select Project Type',
  typeModalMessage: 'Please select the type of cleaning you need:',
  typeRequiredMessage: 'Please select a project type.',
  typeLogLabel: 'project type',
  typeOptions: [
    {
      value: 'repair',
      label: 'Basic Cleaning',
      description: 'General tidying, dusting, vacuuming, and surface cleaning',
      written: 'Basic repair',
    },
    {
      value: 'renovation',
      label: 'Deep Cleaning',
      description: 'Comprehensive cleaning including baseboards, inside appliances, and hard-to-reach areas',
      written: 'Major renovation',
    },
  ],
  typeEnhancedPattern: '\\.\\s*type:\\s*(repair|renovation)\\s*cleaning',
  sizeWrittenLabel: 'Property size',
  sizeExtractPattern: '\\.\\s*Property size:\\s*([^.]+)',
  sizeStripPattern: '\\.\\s*Property size:\\s*[^.]+',
  typeExtractPattern: '\\.\\s*Type:\\s*(Basic|Deep)\\s*cleaning',
  typeStripPattern: '\\.\\s*Type:\\s*(Basic|Deep)\\s*cleaning',
  inferTypeFromDescription: false,
  includeSpelledOutRoomDetection: false,
  sizeDetectPattern: '\\.\\s*scope and complexity of the project:',
  sizeLogLabel: 'scope and complexity of the project',
  bringDetectPattern: '\\.\\s*materials to bring:',
  bringWrittenLabel: 'Materials to bring',
  bringExtractPattern: '\\.\\s*Materials to bring:\\s*([^.]+)',
  bringStripPattern: '\\.\\s*Materials to bring:\\s*[^.]+',
  bringLogLabel: 'materials',
  bringModalTitle: 'Cleaning Materials',
  bringModalMessage: 'What cleaning materials or equipment should your Helpr bring?',
  bringPlaceholder: 'e.g., All cleaning materials, vacuum, mop, eco-friendly products...',
  pricingSystemPrompt: "You are a pricing assistant for home improvement services. Respond with a JSON object containing: price (number), needs_clarification (boolean), clarification_prompt (string, only if needs_clarification is true), safety_concern (boolean), safety_message (string, only if safety_concern is true). Analyze the task description and determine if critical details are missing: 1) type of home improvement work (repair/installation/renovation), 2) specific areas or rooms requiring work, 3) scope and complexity of the project. If any are unclear, set needs_clarification to true and provide a friendly clarification_prompt asking for the missing details. If the request involves hazardous materials, biohazards, or dangerous conditions, set safety_concern to true with an appropriate safety_message. For complete descriptions, provide price in USD (20-250 range). IMPORTANT: Scale prices significantly based on scope and complexity of the project - Studio: $20-40 (repair) / $40-80 (renovation), 1-bed: $30-50 (repair) / $60-100 (renovation), 2-bed: $45-70 (repair) / $90-130 (renovation), 3-bed: $60-90 (repair) / $120-170 (renovation), 4+ bed or house: $80-130 (repair) / $150-250 (renovation). Always increase price proportionally with more bedrooms. Provide competitive, budget-friendly estimates.",
};

export const wallMountingServiceConfig: SingleLocationServiceConfig = {
  returnPath: '/(services)/wall-mounting',
  resumeAction: 'schedule-wall-mounting',
  serviceType: 'wall-mounting',
  servicePhrase: 'wall mounting',
  screenTitle: 'Wall Mounting Details',
  locationPlaceholder: 'Service Location',
  descriptionPlaceholder: "Describe your task...                                         (e.g.  'I need my one bedroom apartment deep cleaned.')",
  typeModalTitle: 'Select Cleaning Type',
  typeModalMessage: 'Please select the type of cleaning you need:',
  typeRequiredMessage: 'Please select a cleaning type.',
  typeLogLabel: 'cleaning type',
  typeOptions: [
    {
      value: 'basic',
      label: 'Basic Cleaning',
      description: 'General tidying, dusting, vacuuming, and surface cleaning',
      written: 'Basic cleaning',
    },
    {
      value: 'deep',
      label: 'Deep Cleaning',
      description: 'Comprehensive cleaning including baseboards, inside appliances, and hard-to-reach areas',
      written: 'Deep cleaning',
    },
  ],
  typeEnhancedPattern: '\\.\\s*type:\\s*(basic|deep)\\s*cleaning',
  sizeWrittenLabel: 'Property size',
  sizeExtractPattern: '\\.\\s*Property size:\\s*([^.]+)',
  sizeStripPattern: '\\.\\s*Property size:\\s*[^.]+',
  typeExtractPattern: '\\.\\s*Type:\\s*(Basic|Deep)\\s*cleaning',
  typeStripPattern: '\\.\\s*Type:\\s*(Basic|Deep)\\s*cleaning',
  inferTypeFromDescription: false,
  includeSpelledOutRoomDetection: false,
  sizeDetectPattern: '\\.\\s*property size:',
  sizeLogLabel: 'property size',
  bringDetectPattern: '\\.\\s*supplies to bring:',
  bringWrittenLabel: 'Supplies to bring',
  bringExtractPattern: '\\.\\s*Supplies to bring:\\s*([^.]+)',
  bringStripPattern: '\\.\\s*Supplies to bring:\\s*[^.]+',
  bringLogLabel: 'supplies',
  bringModalTitle: 'Cleaning Supplies',
  bringModalMessage: 'What cleaning supplies or equipment should your Helpr bring?',
  bringPlaceholder: 'e.g., All cleaning supplies, vacuum, mop, eco-friendly products...',
  pricingSystemPrompt: "You are a pricing assistant for cleaning services. Respond with a JSON object containing: price (number), needs_clarification (boolean), clarification_prompt (string, only if needs_clarification is true), safety_concern (boolean), safety_message (string, only if safety_concern is true). Analyze the task description and determine if critical details are missing: 1) degree of cleaning needed (light/medium/deep), 2) which rooms or entire home, 3) property size. If any are unclear, set needs_clarification to true and provide a friendly clarification_prompt asking for the missing details. If the request involves hazardous materials, biohazards, or dangerous conditions, set safety_concern to true with an appropriate safety_message. For complete descriptions, provide price in USD (20-250 range). IMPORTANT: Scale prices significantly based on property size - Studio: $20-40 (basic) / $40-80 (deep), 1-bed: $30-50 (basic) / $60-100 (deep), 2-bed: $45-70 (basic) / $90-130 (deep), 3-bed: $60-90 (basic) / $120-170 (deep), 4+ bed or house: $80-130 (basic) / $150-250 (deep). Always increase price proportionally with more bedrooms. Provide competitive, budget-friendly estimates.",
};

export const customServiceConfig: RouteServiceConfig = {
  returnPath: '/(services)/custom-service',
  resumeAction: 'schedule-customService',
  serviceType: 'customService',
  servicePhrase: 'customService',
  screenTitle: 'Custom Service Details',
  locationPlaceholder: 'Service Location',
  descriptionPlaceholder: "Describe your task...                                         (e.g.  'I need a mirror mounted on my wall.')",
  pricingSystemPrompt: "You are a pricing assistant for custom service requests. Respond with a JSON object containing: price (number), needs_clarification (boolean), clarification_prompt (string, only if needs_clarification is true), safety_concern (boolean), safety_message (string, only if safety_concern is true). Carefully analyze the task description for the exact scope of work. Use your best judgment to determine if essential details are missing - dynamically adjust what you ask for based on the type of task described. If the description is too vague or missing critical details for that specific type of work, set needs_clarification to true with a clarification_prompt asking for the specific missing information. If the request involves: dangerous activities, illegal activities, licensed professional work (electrical/plumbing/HVAC), hazardous materials, extreme physical risk, or appears priced well above $800, set safety_concern to true. For complete, suitable descriptions, provide price in USD (50-800 range): simple tasks $50-150, medium complexity $150-300, complex tasks $300-800. Provide optimistic, budget-friendly estimates.",
};
